sudo: required
services:
  - docker

before_install:
  - docker build -t consoko/crawling_web -f Dockerfile .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push consoko/crawling_web

script:
  - docker run consoko/crawling_web

#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-1"
#  app: "cl-test"
#  env: "ClTest-env"
#  bucket_name: "elasticbeanstalk-us-east-1-234572293247"
#  bucket_path: "cl-test"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"
