language: generic
sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in tonal-affinity-253116-0e43126a5807.json.enc -out tonal-affinity-253116-0e43126a5807.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file tonal-affinity-253116-0e43126a5807.json
  - gcloud config set project tonal-affinity-253116
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials cluster-test
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master