# Generated by Django 2.1.7 on 2019-06-13 07:54

from django.db import migrations
import front.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission',
            field=front.utils.fields.JSONField(blank=True, null=True),
        ),
    ]
